WSPBuilder -ProjectPath NCNewssiteApplicationPages -SolutionPath NCNewssiteApplicationPages -Outputpath c:\deploy
WSPBuilder -ProjectPath NCNewssiteBranding -SolutionPath NCNewssiteBranding -Outputpath c:\deploy
WSPBuilder -ProjectPath NCNewssiteCommon -SolutionPath NCNewssiteCommon -Outputpath c:\deploy
WSPBuilder -ProjectPath NCNewssiteCore -SolutionPath NCNewssiteCore -Outputpath c:\deploy
WSPBuilder -ProjectPath NCNewssiteFlushCache -SolutionPath NCNewssiteFlushCache -Outputpath c:\deploy
WSPBuilder -ProjectPath NCNewssiteLayout -SolutionPath NCNewssiteLayout -Outputpath c:\deploy
WSPBuilder -ProjectPath NCNewssiteMiniCalendar -SolutionPath NCNewssiteMiniCalendar -Outputpath c:\deploy
WSPBuilder -ProjectPath NCNewssitePatch1 -SolutionPath NCNewssitePatch1 -Outputpath c:\deploy
WSPBuilder -ProjectPath NCNewssitePatch2 -SolutionPath NCNewssitePatch2 -Outputpath c:\deploy
